flowchart LR
  N0["Media-App"]
  N1["source/demux"]
  N0 --> N1
  N2["MediaCodec"]
  N1 --> N2
  N3["video-Surface+AudioTrack"]
  N2 --> N3
  N4["SurfaceFlinger+AudioFlinger"]
  N3 --> N4
  N5["display+DSP/amplifier"]
  N4 --> N5
  N6["user-observation"]
  N5 --> N6
