flowchart LR
  N0["reverse-trigger"]
  N1["Camera/ISP"]
  N0 --> N1
  N2["RVC-pipeline"]
  N1 --> N2
  N3["GStreamer"]
  N2 --> N3
  N4["display-Surface"]
  N3 --> N4
  N5["Weston"]
  N4 --> N5
  N6["DRM/KMS"]
  N5 --> N6
  N7["physical-display"]
  N6 --> N7
