flowchart LR
  N0["Guest-Surface/Buffer"]
  N1["virtual-display-frontend"]
  N0 --> N1
  N2["virtio-descriptor"]
  N1 --> N2
  N3["shared-memory"]
  N2 --> N3
  N4["Hypervisor"]
  N3 --> N4
  N5["Host-Backend"]
  N4 --> N5
  N6["host-compositor"]
  N5 --> N6
  N7["DRM/KMS"]
  N6 --> N7
  N8["physical-display"]
  N7 --> N8
