flowchart LR
  N0["Lifecycle"]
  N1["Cluster-process"]
  N0 --> N1
  N2["CanClient/Client"]
  N1 --> N2
  N3["initial-snapshot"]
  N2 --> N3
  N4["warning-state-machine"]
  N3 --> N4
  N5["Weston"]
  N4 --> N5
  N6["DRM/KMS"]
  N5 --> N6
  N7["physical-display"]
  N6 --> N7
