flowchart LR
  N0["microphone"]
  N1["AudioRecord"]
  N0 --> N1
  N2["AEC-reference"]
  N1 --> N2
  N3["AEC/mix"]
  N2 --> N3
  N4["KTV/ASR"]
  N3 --> N4
  N5["AudioTrack"]
  N4 --> N5
  N6["AudioFlinger"]
  N5 --> N6
  N7["DSP/amplifier"]
  N6 --> N7
  N8["speaker"]
  N7 --> N8
