flowchart LR
  N0["Radio-App"]
  N1["BroadcastRadio-Service/HAL"]
  N0 --> N1
  N2["radio-driver"]
  N1 --> N2
  N3["tuner"]
  N2 --> N3
  N4["metadata"]
  N3 --> N4
  N5["AudioPolicy/AudioFlinger"]
  N4 --> N5
  N6["DSP/amplifier"]
  N5 --> N6
  N7["speaker"]
  N6 --> N7
