flowchart LR
  N0["Audio-App/policy"]
  N1["AudioFlinger"]
  N0 --> N1
  N2["Audio-HAL"]
  N1 --> N2
  N3["ALSA"]
  N2 --> N3
  N4["DSP/Codec"]
  N3 --> N4
  N5["amplifier"]
  N4 --> N5
  N6["speaker"]
  N5 --> N6
  N7["acoustic-output"]
  N6 --> N7
