flowchart LR
  N0["App/View"]
  N1["ViewRootImpl/Choreographer"]
  N0 --> N1
  N2["RenderThread/HWUI"]
  N1 --> N2
  N3["Surface/BufferQueue"]
  N2 --> N3
  N4["SurfaceFlinger"]
  N3 --> N4
  N5["HWC"]
  N4 --> N5
  N6["Display-HAL"]
  N5 --> N6
  N7["DRM/MDP"]
  N6 --> N7
  N8["physical-display"]
  N7 --> N8
