flowchart LR
  N0["Bluetooth-HFP"]
  N1["BtPhone"]
  N0 --> N1
  N2["Telephony/BT-Service"]
  N1 --> N2
  N3["call-state"]
  N2 --> N3
  N4["AudioFocus"]
  N3 --> N4
  N5["Bluetooth-SCO"]
  N4 --> N5
  N6["AudioPolicy/AudioFlinger"]
  N5 --> N6
  N7["DSP"]
  N6 --> N7
  N8["microphone+speaker"]
  N7 --> N8
