flowchart LR
  N0["application/xCall"]
  N1["Favalon-Voice-Client"]
  N0 --> N1
  N2["fb_modemServices"]
  N1 --> N2
  N3["Telephony/Modem"]
  N2 --> N3
  N4["Audio-Service"]
  N3 --> N4
  N5["DSP-route"]
  N4 --> N5
  N6["call-event-callback"]
  N5 --> N6
