flowchart LR
  N0["BootLoader/FBL"]
  N1["Hypervisor/Micro Kernel"]
  N0 --> N1
  N2["SOS/Android/TBox VM"]
  N1 --> N2
  N3["Kernel/systemd/AOSP"]
  N2 --> N3
  N4["服务依赖"]
  N3 --> N4
  N5["Launcher/Cluster/HMI Ready"]
  N4 --> N5
